### ISSUE TITLE
Home Assistant 2021.12.7

### ISSUE THREAD

**Issue by chen-sky** [dscao/autoamap#2]
`Logger: homeassistant.components.device_tracker
Source: custom_components/gaodemap/device_tracker.py:181
Integration: 设备跟踪器 (documentation, issues)
First occurred: 19:16:31 (1 occurrences)
Last logged: 19:16:31

Error setting up platform legacy gaodemap
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 251, in async_setup_legacy
    setup = await self.platform.async_setup_scanner(  # type: ignore[attr-defined]
  File "/config/custom_components/gaodemap/device_tracker.py", line 91, in async_setup_scanner
    await scanner.async_start(hass, interval)
  File "/config/custom_components/gaodemap/device_tracker.py", line 130, in async_start
    await self.async_update_info()
  File "/config/custom_components/gaodemap/device_tracker.py", line 181, in async_update_info
    if ret['data']['carLinkInfoList'][0]['onlineStatus'] == 1:
KeyError: 'carLinkInfoList'`

**Comment by dscao** [comment]
The old version has been deleted and a new version has been rewritten. This problem should no longer exist.
